remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Alexander Trujillo – Software Engineer & Data Enthusiast
description: Building scalable solutions with technology, data science, and APIs. Passionate about solving complex problems through code.
